# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CDTS.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CDTS.proto',
  package='CTA.ACTL.CDTS',
  serialized_pb=_b('\n\nCDTS.proto\x12\rCTA.ACTL.CDTS\"1\n\tTimeStamp\x12\x0f\n\x07seconds\x18\x01 \x02(\x06\x12\x13\n\x0bpicoSeconds\x18\x02 \x02(\x06\"\xd1\x01\n\x0eTriggerMessage\x12\x11\n\ttelescope\x18\x01 \x02(\x07\x12\r\n\x05\x65vent\x18\x02 \x02(\x06\x12&\n\x04time\x18\x03 \x02(\x0b\x32\x18.CTA.ACTL.CDTS.TimeStamp\x12\x37\n\x04type\x18\x04 \x01(\x0e\x32\x1a.CTA.ACTL.CDTS.TriggerType:\rCameraTrigger\x12<\n\x06status\x18\x05 \x01(\x0e\x32 .CTA.ACTL.CDTS.WhiteRabbitStatus:\nTrackPhase\"?\n\x0cTriggerBunch\x12/\n\x08triggers\x18\x01 \x03(\x0b\x32\x1d.CTA.ACTL.CDTS.TriggerMessage*F\n\x0bTriggerType\x12\x11\n\rCameraTrigger\x10\x01\x12\x0f\n\x0bSoftTrigger\x10\x02\x12\x13\n\x0f\x45xternalTrigger\x10\x03*v\n\x11WhiteRabbitStatus\x12\x11\n\rUninitialized\x10\x01\x12\x0c\n\x08SyncNsec\x10\x02\x12\x0b\n\x07SyncSec\x10\x03\x12\r\n\tSyncPhase\x10\x04\x12\x0e\n\nTrackPhase\x10\x05\x12\x14\n\x10WaitOffsetStable\x10\x06')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TRIGGERTYPE = _descriptor.EnumDescriptor(
  name='TriggerType',
  full_name='CTA.ACTL.CDTS.TriggerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CameraTrigger', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SoftTrigger', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ExternalTrigger', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=357,
  serialized_end=427,
)
_sym_db.RegisterEnumDescriptor(_TRIGGERTYPE)

TriggerType = enum_type_wrapper.EnumTypeWrapper(_TRIGGERTYPE)
_WHITERABBITSTATUS = _descriptor.EnumDescriptor(
  name='WhiteRabbitStatus',
  full_name='CTA.ACTL.CDTS.WhiteRabbitStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Uninitialized', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SyncNsec', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SyncSec', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SyncPhase', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TrackPhase', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WaitOffsetStable', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=429,
  serialized_end=547,
)
_sym_db.RegisterEnumDescriptor(_WHITERABBITSTATUS)

WhiteRabbitStatus = enum_type_wrapper.EnumTypeWrapper(_WHITERABBITSTATUS)
CameraTrigger = 1
SoftTrigger = 2
ExternalTrigger = 3
Uninitialized = 1
SyncNsec = 2
SyncSec = 3
SyncPhase = 4
TrackPhase = 5
WaitOffsetStable = 6



_TIMESTAMP = _descriptor.Descriptor(
  name='TimeStamp',
  full_name='CTA.ACTL.CDTS.TimeStamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='CTA.ACTL.CDTS.TimeStamp.seconds', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='picoSeconds', full_name='CTA.ACTL.CDTS.TimeStamp.picoSeconds', index=1,
      number=2, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=78,
)


_TRIGGERMESSAGE = _descriptor.Descriptor(
  name='TriggerMessage',
  full_name='CTA.ACTL.CDTS.TriggerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='telescope', full_name='CTA.ACTL.CDTS.TriggerMessage.telescope', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event', full_name='CTA.ACTL.CDTS.TriggerMessage.event', index=1,
      number=2, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='CTA.ACTL.CDTS.TriggerMessage.time', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='CTA.ACTL.CDTS.TriggerMessage.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='CTA.ACTL.CDTS.TriggerMessage.status', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=290,
)


_TRIGGERBUNCH = _descriptor.Descriptor(
  name='TriggerBunch',
  full_name='CTA.ACTL.CDTS.TriggerBunch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='triggers', full_name='CTA.ACTL.CDTS.TriggerBunch.triggers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=355,
)

_TRIGGERMESSAGE.fields_by_name['time'].message_type = _TIMESTAMP
_TRIGGERMESSAGE.fields_by_name['type'].enum_type = _TRIGGERTYPE
_TRIGGERMESSAGE.fields_by_name['status'].enum_type = _WHITERABBITSTATUS
_TRIGGERBUNCH.fields_by_name['triggers'].message_type = _TRIGGERMESSAGE
DESCRIPTOR.message_types_by_name['TimeStamp'] = _TIMESTAMP
DESCRIPTOR.message_types_by_name['TriggerMessage'] = _TRIGGERMESSAGE
DESCRIPTOR.message_types_by_name['TriggerBunch'] = _TRIGGERBUNCH
DESCRIPTOR.enum_types_by_name['TriggerType'] = _TRIGGERTYPE
DESCRIPTOR.enum_types_by_name['WhiteRabbitStatus'] = _WHITERABBITSTATUS

TimeStamp = _reflection.GeneratedProtocolMessageType('TimeStamp', (_message.Message,), dict(
  DESCRIPTOR = _TIMESTAMP,
  __module__ = 'CDTS_pb2'
  # @@protoc_insertion_point(class_scope:CTA.ACTL.CDTS.TimeStamp)
  ))
_sym_db.RegisterMessage(TimeStamp)

TriggerMessage = _reflection.GeneratedProtocolMessageType('TriggerMessage', (_message.Message,), dict(
  DESCRIPTOR = _TRIGGERMESSAGE,
  __module__ = 'CDTS_pb2'
  # @@protoc_insertion_point(class_scope:CTA.ACTL.CDTS.TriggerMessage)
  ))
_sym_db.RegisterMessage(TriggerMessage)

TriggerBunch = _reflection.GeneratedProtocolMessageType('TriggerBunch', (_message.Message,), dict(
  DESCRIPTOR = _TRIGGERBUNCH,
  __module__ = 'CDTS_pb2'
  # @@protoc_insertion_point(class_scope:CTA.ACTL.CDTS.TriggerBunch)
  ))
_sym_db.RegisterMessage(TriggerBunch)


# @@protoc_insertion_point(module_scope)
